version: '3'
services:
  db:
    container_name: postgres_DB
    image: postgres:latest
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
  app-lyrics:
    image: app-lyrics:latest
    container_name: app_lyrics_app
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - db


